// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hub_to_agent.proto

package idl

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpgradePrimariesRequest struct {
	OldBinDir            string         `protobuf:"bytes,1,opt,name=OldBinDir" json:"OldBinDir,omitempty"`
	NewBinDir            string         `protobuf:"bytes,2,opt,name=NewBinDir" json:"NewBinDir,omitempty"`
	NewVersion           string         `protobuf:"bytes,3,opt,name=NewVersion" json:"NewVersion,omitempty"`
	DataDirPairs         []*DataDirPair `protobuf:"bytes,4,rep,name=DataDirPairs" json:"DataDirPairs,omitempty"`
	CheckOnly            bool           `protobuf:"varint,5,opt,name=CheckOnly" json:"CheckOnly,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpgradePrimariesRequest) Reset()         { *m = UpgradePrimariesRequest{} }
func (m *UpgradePrimariesRequest) String() string { return proto.CompactTextString(m) }
func (*UpgradePrimariesRequest) ProtoMessage()    {}
func (*UpgradePrimariesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_2e2f0ee2edb15dae, []int{0}
}
func (m *UpgradePrimariesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradePrimariesRequest.Unmarshal(m, b)
}
func (m *UpgradePrimariesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradePrimariesRequest.Marshal(b, m, deterministic)
}
func (dst *UpgradePrimariesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradePrimariesRequest.Merge(dst, src)
}
func (m *UpgradePrimariesRequest) XXX_Size() int {
	return xxx_messageInfo_UpgradePrimariesRequest.Size(m)
}
func (m *UpgradePrimariesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradePrimariesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradePrimariesRequest proto.InternalMessageInfo

func (m *UpgradePrimariesRequest) GetOldBinDir() string {
	if m != nil {
		return m.OldBinDir
	}
	return ""
}

func (m *UpgradePrimariesRequest) GetNewBinDir() string {
	if m != nil {
		return m.NewBinDir
	}
	return ""
}

func (m *UpgradePrimariesRequest) GetNewVersion() string {
	if m != nil {
		return m.NewVersion
	}
	return ""
}

func (m *UpgradePrimariesRequest) GetDataDirPairs() []*DataDirPair {
	if m != nil {
		return m.DataDirPairs
	}
	return nil
}

func (m *UpgradePrimariesRequest) GetCheckOnly() bool {
	if m != nil {
		return m.CheckOnly
	}
	return false
}

type DataDirPair struct {
	OldDataDir           string   `protobuf:"bytes,1,opt,name=OldDataDir" json:"OldDataDir,omitempty"`
	NewDataDir           string   `protobuf:"bytes,2,opt,name=NewDataDir" json:"NewDataDir,omitempty"`
	OldPort              int32    `protobuf:"varint,3,opt,name=OldPort" json:"OldPort,omitempty"`
	NewPort              int32    `protobuf:"varint,4,opt,name=NewPort" json:"NewPort,omitempty"`
	Content              int32    `protobuf:"varint,5,opt,name=Content" json:"Content,omitempty"`
	DBID                 int32    `protobuf:"varint,6,opt,name=DBID" json:"DBID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataDirPair) Reset()         { *m = DataDirPair{} }
func (m *DataDirPair) String() string { return proto.CompactTextString(m) }
func (*DataDirPair) ProtoMessage()    {}
func (*DataDirPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_2e2f0ee2edb15dae, []int{1}
}
func (m *DataDirPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataDirPair.Unmarshal(m, b)
}
func (m *DataDirPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataDirPair.Marshal(b, m, deterministic)
}
func (dst *DataDirPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataDirPair.Merge(dst, src)
}
func (m *DataDirPair) XXX_Size() int {
	return xxx_messageInfo_DataDirPair.Size(m)
}
func (m *DataDirPair) XXX_DiscardUnknown() {
	xxx_messageInfo_DataDirPair.DiscardUnknown(m)
}

var xxx_messageInfo_DataDirPair proto.InternalMessageInfo

func (m *DataDirPair) GetOldDataDir() string {
	if m != nil {
		return m.OldDataDir
	}
	return ""
}

func (m *DataDirPair) GetNewDataDir() string {
	if m != nil {
		return m.NewDataDir
	}
	return ""
}

func (m *DataDirPair) GetOldPort() int32 {
	if m != nil {
		return m.OldPort
	}
	return 0
}

func (m *DataDirPair) GetNewPort() int32 {
	if m != nil {
		return m.NewPort
	}
	return 0
}

func (m *DataDirPair) GetContent() int32 {
	if m != nil {
		return m.Content
	}
	return 0
}

func (m *DataDirPair) GetDBID() int32 {
	if m != nil {
		return m.DBID
	}
	return 0
}

type UpgradePrimariesReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradePrimariesReply) Reset()         { *m = UpgradePrimariesReply{} }
func (m *UpgradePrimariesReply) String() string { return proto.CompactTextString(m) }
func (*UpgradePrimariesReply) ProtoMessage()    {}
func (*UpgradePrimariesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_2e2f0ee2edb15dae, []int{2}
}
func (m *UpgradePrimariesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradePrimariesReply.Unmarshal(m, b)
}
func (m *UpgradePrimariesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradePrimariesReply.Marshal(b, m, deterministic)
}
func (dst *UpgradePrimariesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradePrimariesReply.Merge(dst, src)
}
func (m *UpgradePrimariesReply) XXX_Size() int {
	return xxx_messageInfo_UpgradePrimariesReply.Size(m)
}
func (m *UpgradePrimariesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradePrimariesReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradePrimariesReply proto.InternalMessageInfo

type CreateSegmentDataDirRequest struct {
	Datadirs             []string `protobuf:"bytes,1,rep,name=datadirs" json:"datadirs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSegmentDataDirRequest) Reset()         { *m = CreateSegmentDataDirRequest{} }
func (m *CreateSegmentDataDirRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSegmentDataDirRequest) ProtoMessage()    {}
func (*CreateSegmentDataDirRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_2e2f0ee2edb15dae, []int{3}
}
func (m *CreateSegmentDataDirRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSegmentDataDirRequest.Unmarshal(m, b)
}
func (m *CreateSegmentDataDirRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSegmentDataDirRequest.Marshal(b, m, deterministic)
}
func (dst *CreateSegmentDataDirRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSegmentDataDirRequest.Merge(dst, src)
}
func (m *CreateSegmentDataDirRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSegmentDataDirRequest.Size(m)
}
func (m *CreateSegmentDataDirRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSegmentDataDirRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSegmentDataDirRequest proto.InternalMessageInfo

func (m *CreateSegmentDataDirRequest) GetDatadirs() []string {
	if m != nil {
		return m.Datadirs
	}
	return nil
}

type CreateSegmentDataDirReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSegmentDataDirReply) Reset()         { *m = CreateSegmentDataDirReply{} }
func (m *CreateSegmentDataDirReply) String() string { return proto.CompactTextString(m) }
func (*CreateSegmentDataDirReply) ProtoMessage()    {}
func (*CreateSegmentDataDirReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_2e2f0ee2edb15dae, []int{4}
}
func (m *CreateSegmentDataDirReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSegmentDataDirReply.Unmarshal(m, b)
}
func (m *CreateSegmentDataDirReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSegmentDataDirReply.Marshal(b, m, deterministic)
}
func (dst *CreateSegmentDataDirReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSegmentDataDirReply.Merge(dst, src)
}
func (m *CreateSegmentDataDirReply) XXX_Size() int {
	return xxx_messageInfo_CreateSegmentDataDirReply.Size(m)
}
func (m *CreateSegmentDataDirReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSegmentDataDirReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSegmentDataDirReply proto.InternalMessageInfo

type CopyMasterRequest struct {
	MasterDir            string   `protobuf:"bytes,1,opt,name=masterDir" json:"masterDir,omitempty"`
	Datadirs             []string `protobuf:"bytes,2,rep,name=datadirs" json:"datadirs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyMasterRequest) Reset()         { *m = CopyMasterRequest{} }
func (m *CopyMasterRequest) String() string { return proto.CompactTextString(m) }
func (*CopyMasterRequest) ProtoMessage()    {}
func (*CopyMasterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_2e2f0ee2edb15dae, []int{5}
}
func (m *CopyMasterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyMasterRequest.Unmarshal(m, b)
}
func (m *CopyMasterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyMasterRequest.Marshal(b, m, deterministic)
}
func (dst *CopyMasterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyMasterRequest.Merge(dst, src)
}
func (m *CopyMasterRequest) XXX_Size() int {
	return xxx_messageInfo_CopyMasterRequest.Size(m)
}
func (m *CopyMasterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyMasterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyMasterRequest proto.InternalMessageInfo

func (m *CopyMasterRequest) GetMasterDir() string {
	if m != nil {
		return m.MasterDir
	}
	return ""
}

func (m *CopyMasterRequest) GetDatadirs() []string {
	if m != nil {
		return m.Datadirs
	}
	return nil
}

type CopyMasterReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyMasterReply) Reset()         { *m = CopyMasterReply{} }
func (m *CopyMasterReply) String() string { return proto.CompactTextString(m) }
func (*CopyMasterReply) ProtoMessage()    {}
func (*CopyMasterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_2e2f0ee2edb15dae, []int{6}
}
func (m *CopyMasterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyMasterReply.Unmarshal(m, b)
}
func (m *CopyMasterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyMasterReply.Marshal(b, m, deterministic)
}
func (dst *CopyMasterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyMasterReply.Merge(dst, src)
}
func (m *CopyMasterReply) XXX_Size() int {
	return xxx_messageInfo_CopyMasterReply.Size(m)
}
func (m *CopyMasterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyMasterReply.DiscardUnknown(m)
}

var xxx_messageInfo_CopyMasterReply proto.InternalMessageInfo

type StopAgentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopAgentRequest) Reset()         { *m = StopAgentRequest{} }
func (m *StopAgentRequest) String() string { return proto.CompactTextString(m) }
func (*StopAgentRequest) ProtoMessage()    {}
func (*StopAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_2e2f0ee2edb15dae, []int{7}
}
func (m *StopAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopAgentRequest.Unmarshal(m, b)
}
func (m *StopAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopAgentRequest.Marshal(b, m, deterministic)
}
func (dst *StopAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopAgentRequest.Merge(dst, src)
}
func (m *StopAgentRequest) XXX_Size() int {
	return xxx_messageInfo_StopAgentRequest.Size(m)
}
func (m *StopAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopAgentRequest proto.InternalMessageInfo

type StopAgentReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopAgentReply) Reset()         { *m = StopAgentReply{} }
func (m *StopAgentReply) String() string { return proto.CompactTextString(m) }
func (*StopAgentReply) ProtoMessage()    {}
func (*StopAgentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_2e2f0ee2edb15dae, []int{8}
}
func (m *StopAgentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopAgentReply.Unmarshal(m, b)
}
func (m *StopAgentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopAgentReply.Marshal(b, m, deterministic)
}
func (dst *StopAgentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopAgentReply.Merge(dst, src)
}
func (m *StopAgentReply) XXX_Size() int {
	return xxx_messageInfo_StopAgentReply.Size(m)
}
func (m *StopAgentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StopAgentReply.DiscardUnknown(m)
}

var xxx_messageInfo_StopAgentReply proto.InternalMessageInfo

type CheckSegmentDiskSpaceRequest struct {
	Request              *CheckDiskSpaceRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Datadirs             []string               `protobuf:"bytes,2,rep,name=datadirs" json:"datadirs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CheckSegmentDiskSpaceRequest) Reset()         { *m = CheckSegmentDiskSpaceRequest{} }
func (m *CheckSegmentDiskSpaceRequest) String() string { return proto.CompactTextString(m) }
func (*CheckSegmentDiskSpaceRequest) ProtoMessage()    {}
func (*CheckSegmentDiskSpaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_2e2f0ee2edb15dae, []int{9}
}
func (m *CheckSegmentDiskSpaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckSegmentDiskSpaceRequest.Unmarshal(m, b)
}
func (m *CheckSegmentDiskSpaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckSegmentDiskSpaceRequest.Marshal(b, m, deterministic)
}
func (dst *CheckSegmentDiskSpaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckSegmentDiskSpaceRequest.Merge(dst, src)
}
func (m *CheckSegmentDiskSpaceRequest) XXX_Size() int {
	return xxx_messageInfo_CheckSegmentDiskSpaceRequest.Size(m)
}
func (m *CheckSegmentDiskSpaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckSegmentDiskSpaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckSegmentDiskSpaceRequest proto.InternalMessageInfo

func (m *CheckSegmentDiskSpaceRequest) GetRequest() *CheckDiskSpaceRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *CheckSegmentDiskSpaceRequest) GetDatadirs() []string {
	if m != nil {
		return m.Datadirs
	}
	return nil
}

func init() {
	proto.RegisterType((*UpgradePrimariesRequest)(nil), "idl.UpgradePrimariesRequest")
	proto.RegisterType((*DataDirPair)(nil), "idl.DataDirPair")
	proto.RegisterType((*UpgradePrimariesReply)(nil), "idl.UpgradePrimariesReply")
	proto.RegisterType((*CreateSegmentDataDirRequest)(nil), "idl.CreateSegmentDataDirRequest")
	proto.RegisterType((*CreateSegmentDataDirReply)(nil), "idl.CreateSegmentDataDirReply")
	proto.RegisterType((*CopyMasterRequest)(nil), "idl.CopyMasterRequest")
	proto.RegisterType((*CopyMasterReply)(nil), "idl.CopyMasterReply")
	proto.RegisterType((*StopAgentRequest)(nil), "idl.StopAgentRequest")
	proto.RegisterType((*StopAgentReply)(nil), "idl.StopAgentReply")
	proto.RegisterType((*CheckSegmentDiskSpaceRequest)(nil), "idl.CheckSegmentDiskSpaceRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Agent service

type AgentClient interface {
	CheckDiskSpace(ctx context.Context, in *CheckSegmentDiskSpaceRequest, opts ...grpc.CallOption) (*CheckDiskSpaceReply, error)
	UpgradePrimaries(ctx context.Context, in *UpgradePrimariesRequest, opts ...grpc.CallOption) (*UpgradePrimariesReply, error)
	CreateSegmentDataDirectories(ctx context.Context, in *CreateSegmentDataDirRequest, opts ...grpc.CallOption) (*CreateSegmentDataDirReply, error)
	CopyMaster(ctx context.Context, in *CopyMasterRequest, opts ...grpc.CallOption) (*CopyMasterReply, error)
	StopAgent(ctx context.Context, in *StopAgentRequest, opts ...grpc.CallOption) (*StopAgentReply, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) CheckDiskSpace(ctx context.Context, in *CheckSegmentDiskSpaceRequest, opts ...grpc.CallOption) (*CheckDiskSpaceReply, error) {
	out := new(CheckDiskSpaceReply)
	err := grpc.Invoke(ctx, "/idl.Agent/CheckDiskSpace", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) UpgradePrimaries(ctx context.Context, in *UpgradePrimariesRequest, opts ...grpc.CallOption) (*UpgradePrimariesReply, error) {
	out := new(UpgradePrimariesReply)
	err := grpc.Invoke(ctx, "/idl.Agent/UpgradePrimaries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) CreateSegmentDataDirectories(ctx context.Context, in *CreateSegmentDataDirRequest, opts ...grpc.CallOption) (*CreateSegmentDataDirReply, error) {
	out := new(CreateSegmentDataDirReply)
	err := grpc.Invoke(ctx, "/idl.Agent/CreateSegmentDataDirectories", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) CopyMaster(ctx context.Context, in *CopyMasterRequest, opts ...grpc.CallOption) (*CopyMasterReply, error) {
	out := new(CopyMasterReply)
	err := grpc.Invoke(ctx, "/idl.Agent/CopyMaster", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) StopAgent(ctx context.Context, in *StopAgentRequest, opts ...grpc.CallOption) (*StopAgentReply, error) {
	out := new(StopAgentReply)
	err := grpc.Invoke(ctx, "/idl.Agent/StopAgent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Agent service

type AgentServer interface {
	CheckDiskSpace(context.Context, *CheckSegmentDiskSpaceRequest) (*CheckDiskSpaceReply, error)
	UpgradePrimaries(context.Context, *UpgradePrimariesRequest) (*UpgradePrimariesReply, error)
	CreateSegmentDataDirectories(context.Context, *CreateSegmentDataDirRequest) (*CreateSegmentDataDirReply, error)
	CopyMaster(context.Context, *CopyMasterRequest) (*CopyMasterReply, error)
	StopAgent(context.Context, *StopAgentRequest) (*StopAgentReply, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_CheckDiskSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSegmentDiskSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CheckDiskSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/CheckDiskSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CheckDiskSpace(ctx, req.(*CheckSegmentDiskSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_UpgradePrimaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradePrimariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).UpgradePrimaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/UpgradePrimaries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).UpgradePrimaries(ctx, req.(*UpgradePrimariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_CreateSegmentDataDirectories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSegmentDataDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CreateSegmentDataDirectories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/CreateSegmentDataDirectories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CreateSegmentDataDirectories(ctx, req.(*CreateSegmentDataDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_CopyMaster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyMasterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CopyMaster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/CopyMaster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CopyMaster(ctx, req.(*CopyMasterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_StopAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).StopAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/StopAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).StopAgent(ctx, req.(*StopAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "idl.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckDiskSpace",
			Handler:    _Agent_CheckDiskSpace_Handler,
		},
		{
			MethodName: "UpgradePrimaries",
			Handler:    _Agent_UpgradePrimaries_Handler,
		},
		{
			MethodName: "CreateSegmentDataDirectories",
			Handler:    _Agent_CreateSegmentDataDirectories_Handler,
		},
		{
			MethodName: "CopyMaster",
			Handler:    _Agent_CopyMaster_Handler,
		},
		{
			MethodName: "StopAgent",
			Handler:    _Agent_StopAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hub_to_agent.proto",
}

func init() { proto.RegisterFile("hub_to_agent.proto", fileDescriptor_hub_to_agent_2e2f0ee2edb15dae) }

var fileDescriptor_hub_to_agent_2e2f0ee2edb15dae = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x41, 0x6f, 0xda, 0x4c,
	0x10, 0xfd, 0x8c, 0x21, 0x09, 0xc3, 0xa7, 0xd4, 0xd9, 0x36, 0x8d, 0xeb, 0xa0, 0xc8, 0xf5, 0x89,
	0x13, 0x07, 0x9a, 0x4b, 0xa4, 0x5e, 0x1a, 0x7c, 0xe9, 0x21, 0x18, 0x19, 0xb5, 0xd7, 0x68, 0xc1,
	0x23, 0x58, 0xc5, 0xd8, 0xee, 0x7a, 0x11, 0xe2, 0x07, 0xf4, 0xf7, 0xf4, 0x77, 0xf4, 0x5f, 0x55,
	0xbb, 0x6b, 0x1b, 0xe3, 0x40, 0x6e, 0xde, 0xf7, 0xde, 0xcc, 0xbc, 0xdd, 0x37, 0x00, 0x64, 0xb5,
	0x99, 0x3f, 0x8b, 0xf4, 0x99, 0x2e, 0x31, 0x11, 0xc3, 0x8c, 0xa7, 0x22, 0x25, 0x26, 0x8b, 0x62,
	0xc7, 0x5a, 0xc4, 0x4c, 0x12, 0xab, 0xcd, 0x5c, 0xc3, 0xde, 0x5f, 0x03, 0x6e, 0x7e, 0x64, 0x4b,
	0x4e, 0x23, 0x9c, 0x72, 0xb6, 0xa6, 0x9c, 0x61, 0x1e, 0xe2, 0xaf, 0x0d, 0xe6, 0x82, 0xf4, 0xa1,
	0x1b, 0xc4, 0xd1, 0x23, 0x4b, 0x7c, 0xc6, 0x6d, 0xc3, 0x35, 0x06, 0xdd, 0x70, 0x0f, 0x48, 0x76,
	0x82, 0xdb, 0x82, 0x6d, 0x69, 0xb6, 0x02, 0xc8, 0x1d, 0xc0, 0x04, 0xb7, 0x3f, 0x91, 0xe7, 0x2c,
	0x4d, 0x6c, 0x53, 0xd1, 0x35, 0x84, 0xdc, 0xc3, 0xff, 0x3e, 0x15, 0xd4, 0x67, 0x7c, 0x4a, 0x19,
	0xcf, 0xed, 0xb6, 0x6b, 0x0e, 0x7a, 0x23, 0x6b, 0xc8, 0xa2, 0x78, 0x58, 0x23, 0xc2, 0x03, 0x95,
	0x9c, 0x39, 0x5e, 0xe1, 0xe2, 0x25, 0x48, 0xe2, 0x9d, 0xdd, 0x71, 0x8d, 0xc1, 0x45, 0xb8, 0x07,
	0xbc, 0x3f, 0x06, 0xf4, 0x6a, 0x72, 0xe9, 0x21, 0x88, 0xa3, 0x02, 0x29, 0x2e, 0x50, 0x43, 0x0a,
	0x8f, 0x25, 0xdf, 0xaa, 0x3c, 0x96, 0xbc, 0x0d, 0xe7, 0x41, 0x1c, 0x4d, 0x53, 0x2e, 0xd4, 0x05,
	0x3a, 0x61, 0x79, 0x94, 0xcc, 0x04, 0xb7, 0x8a, 0x69, 0x6b, 0xa6, 0x38, 0x4a, 0x66, 0x9c, 0x26,
	0x02, 0x13, 0xa1, 0xfc, 0x75, 0xc2, 0xf2, 0x48, 0x08, 0xb4, 0xfd, 0xc7, 0xef, 0xbe, 0x7d, 0xa6,
	0x60, 0xf5, 0xed, 0xdd, 0xc0, 0xf5, 0xeb, 0xc7, 0xcf, 0xe2, 0x9d, 0xf7, 0x00, 0xb7, 0x63, 0x8e,
	0x54, 0xe0, 0x0c, 0x97, 0x6b, 0x4c, 0x44, 0x61, 0xa9, 0x4c, 0xc6, 0x81, 0x8b, 0x88, 0x0a, 0x1a,
	0xc9, 0x97, 0x33, 0x5c, 0x73, 0xd0, 0x0d, 0xab, 0xb3, 0x77, 0x0b, 0x9f, 0x8e, 0x97, 0xca, 0xbe,
	0x4f, 0x70, 0x35, 0x4e, 0xb3, 0xdd, 0x13, 0xcd, 0x05, 0xf2, 0x5a, 0xce, 0x6b, 0x05, 0xd4, 0x72,
	0xae, 0x80, 0x83, 0x59, 0xad, 0xc6, 0xac, 0x2b, 0x78, 0x57, 0x6f, 0x27, 0x27, 0x10, 0xb0, 0x66,
	0x22, 0xcd, 0xbe, 0xc9, 0xd5, 0x2b, 0x06, 0x78, 0x16, 0x5c, 0xd6, 0x30, 0xa9, 0xca, 0xa0, 0xaf,
	0x72, 0x2b, 0x3d, 0xb2, 0xfc, 0x65, 0x96, 0xd1, 0x05, 0x96, 0x96, 0xee, 0xe1, 0x9c, 0xeb, 0x4f,
	0x65, 0xa8, 0x37, 0x72, 0xd4, 0x66, 0xa8, 0x9a, 0xa6, 0x38, 0x2c, 0xa5, 0x6f, 0x59, 0x1d, 0xfd,
	0x36, 0xa1, 0xa3, 0x0c, 0x90, 0x00, 0x2e, 0x0f, 0xfb, 0x90, 0xcf, 0xfb, 0xe6, 0x27, 0x0c, 0x39,
	0xf6, 0xd1, 0xf9, 0xf2, 0x2a, 0xff, 0x91, 0x09, 0x58, 0xcd, 0x14, 0x49, 0x5f, 0xe9, 0x4f, 0xfc,
	0xb2, 0x1c, 0xe7, 0x04, 0xab, 0xfb, 0xcd, 0xa1, 0x7f, 0x2c, 0x41, 0x5c, 0x88, 0x54, 0xf5, 0x76,
	0xb5, 0x97, 0xd3, 0xfb, 0xe1, 0xdc, 0xbd, 0xa1, 0xd0, 0x33, 0xbe, 0x02, 0xec, 0x93, 0x23, 0x1f,
	0xb5, 0xbe, 0xb9, 0x19, 0xce, 0x87, 0x57, 0xb8, 0xae, 0x7e, 0x80, 0x6e, 0x15, 0x28, 0xb9, 0x56,
	0xa2, 0x66, 0xe8, 0xce, 0xfb, 0x26, 0xac, 0x4a, 0xe7, 0x67, 0xea, 0x7f, 0xe7, 0xcb, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xbd, 0x5c, 0x84, 0x29, 0xa4, 0x04, 0x00, 0x00,
}
