---
# Copyright (c) 2017-2020 VMware, Inc. or its affiliates
# SPDX-License-Identifier: Apache-2.0

resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.11.14

resources:
- name: gpupgrade_src
  type: git
  source:
    uri: ((gpupgrade-git-remote))
    branch: ((gpupgrade-git-branch))
    fetch_tags: true

{{range .AllVersions}}
- name: gpdb{{.}}_src
  type: git
  source:
    uri: https://github.com/greenplum-db/gpdb
    branch: {{.}}X_STABLE
{{end}}

- name: retail_demo_src
  type: git
  source:
    uri: ((retail-demo-git-remote))
    private_key: ((retail-demo-git-key))
    branch: ((retail-demo-git-branch))

{{range .Versions}}
{{- if eq (majorVersion .GPVersion) "5" }}
- name: rpm_gpdb{{.GPVersion}}_centos{{.CentosVersion}}
  type: s3
  source:
    access_key_id: ((bucket-access-key-id))
    bucket: ((gpdb-stable-builds-bucket-name))
    region_name: ((aws-region))
    secret_access_key: ((bucket-secret-access-key))
    regexp: release_candidates/gpdb_rpm_installer_centos{{.CentosVersion}}/gpdb{{ majorVersion .GPVersion }}/greenplum-db-({{escapeVersion .GPVersion}}.*)-rhel{{.CentosVersion}}-x86_64.rpm
{{- else }}
- name: rpm_gpdb{{.GPVersion}}_centos{{.CentosVersion}}
  type: gcs
  source:
    bucket: ((gcs-bucket))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: server/published/gpdb{{ majorVersion .GPVersion }}/greenplum-db-({{escapeVersion .GPVersion}}.*)-rhel{{.CentosVersion}}-x86_64.debug.rpm
{{- end }}
{{end}}

- name: bin_gpupgrade
  type: gcs
  source:
    bucket: ((cm-intermediates-bucket))
    json_key: ((cm-gcs-service-account-key))
    versioned_file: gpupgrade

- name: rpm_gpupgrade_oss
  type: gcs
  source:
    bucket: ((cm-intermediates-bucket))
    json_key: ((cm-gcs-service-account-key))
    regexp: oss/greenplum-upgrade-(.*).rpm

- name: rpm_gpupgrade_enterprise
  type: gcs
  source:
    bucket: ((cm-intermediates-bucket))
    json_key: ((cm-gcs-service-account-key))
    regexp: enterprise/greenplum-upgrade-(.*).rpm

- name: bin_gpupgrade_rc
  type: gcs
  source:
    bucket: ((cm-artifacts-bucket))
    json_key: ((cm-gcs-service-account-key))
    regexp: release-candidates/gpupgrade-rc-(.*)-linux_x86_64

- name: bats
  type: git
  source:
    uri: https://github.com/bats-core/bats-core
    branch: master
    tag_filter: v1.*

- name: slack-alert
  type: slack-notification
  source:
    url: ((cm_webhook_url))

- name: ccp_src
  type: git
  source:
    branch: ((ccp-git-branch))
    private_key: ((ccp-git-key))
    uri: ((ccp-git-remote))

- name: terraform
  type: terraform
  source:
    env:
      AWS_ACCESS_KEY_ID: ((tf-machine-access-key-id))
      AWS_SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
      GOOGLE_CREDENTIALS: ((google-service-account-key))
    vars:
      project_id: ((google-project-id))
    storage:
      access_key_id: ((tf-machine-access-key-id))
      secret_access_key: ((tf-machine-secret-access-key))
      region_name: ((aws-region))
      # This is not parameterized, on purpose. All tfstates will go to this spot,
      # and different teams will place there clusters' tfstate files under different paths
      bucket: gpdb5-pipeline-dynamic-terraform
      bucket_path: clusters-google/

- name: gpdb5_icw_planner_centos6_dump
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: 5X_STABLE/icw_planner_centos6_dump/dump.sql.xz

- name: dump_gpdb6_icw_gporca_centos6
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: 6X_STABLE/icw_gporca_centos6_dump/dump.sql.xz

anchors:
  - &ccp_default_params
    action: create
    delete_on_failure: true
    generate_random_name: true
    terraform_source: ccp_src/google/

  - &ccp_gen_cluster_default_params
    AWS_ACCESS_KEY_ID: ((tf-machine-access-key-id))
    AWS_SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
    AWS_DEFAULT_REGION: ((aws-region))
    BUCKET_PATH: clusters-google/
    BUCKET_NAME: ((tf-bucket-name))
    CLOUD_PROVIDER: google

  - &ccp_destroy
    put: terraform
    params:
      action: destroy
      env_name_file: terraform/name
      terraform_source: ccp_src/google/
      vars:
        aws_instance-node-instance_type: t2.micro #t2.micro is ignored in destroy, but aws_instance-node-instance_type is required.
        aws_ebs_volume_type: standard
    get_params:
      action: destroy

  - &set_failed
    do:
      - task: on_failure_set_failed
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotaldata/ccp
              tag: "7"
          inputs:
            - name: ccp_src
            - name: terraform
          run:
            path: 'ccp_src/google/ccp_failed_test.sh'
          params:
            GOOGLE_CREDENTIALS: ((google-service-account-key))
            GOOGLE_PROJECT_ID: ((google-project-id))
            GOOGLE_ZONE: ((google-zone))
            GOOGLE_SERVICE_ACCOUNT: ((google-service-account))
            AWS_ACCESS_KEY_ID: ((tf-machine-access-key-id))
            AWS_SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
            AWS_DEFAULT_REGION: ((tf-machine-region))
            BUCKET_PATH: clusters-google/
            BUCKET_NAME: ((tf-bucket-name))

  - &slack_alert
    do:
      - put: slack-alert
        params:
          text: |
            Hey team, <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|gpupgrade/$BUILD_JOB_NAME> failed.

groups:
  - name: all
    jobs:
      - build
      - lint
      - noinstall-tests
      {{- range .CheckJobs}}
      - {{.Name}}
      {{- end}}
      {{- range .MultihostBatsJobs}}
      - {{.Name}}
      {{- end}}
      {{- range .UpgradeJobs}}
      - {{.Name}}
      {{- end}}
      - publish-release-candidate
  - name: bats
    jobs:
      {{- range .CheckJobs}}
      - {{.Name}}
      {{- end}}
      {{- range .MultihostBatsJobs}}
      - {{.Name}}
      {{- end}}
  - name: upgrade
    jobs:
      - build
      {{- range .UpgradeJobs}}
      {{- if not .RetailDemo}}
      - {{.Name}}
      {{- end}}
      {{- end}}
  - name: functional
    jobs:
      - build
      {{- range .UpgradeJobs}}
      {{- if .RetailDemo}}
      - {{.Name}}
      {{- end}}
      {{- end}}

jobs:
- name: build
  plan:
  - get: gpupgrade_src
    trigger: true
  - task: build
    file: gpupgrade_src/ci/tasks/build.yml
  - in_parallel:
    - put: bin_gpupgrade
      params:
        file: build_artifacts/gpupgrade
    - put: rpm_gpupgrade_oss
      params:
        file: build_artifacts_oss/greenplum-upgrade*.rpm
    - put: rpm_gpupgrade_enterprise
      params:
        file: build_artifacts_enterprise/greenplum-upgrade*.rpm
  on_failure:
    <<: *slack_alert

- name: lint
  plan:
  - get: gpupgrade_src
    trigger: true
  - task: lint
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golangci/golangci-lint
      inputs:
        - name: gpupgrade_src
      run:
        path: bash
        args:
          - -c
          - |
            set -ex

            cd gpupgrade_src
            make lint
  on_failure:
    <<: *slack_alert

- name: noinstall-tests
  plan:
  - in_parallel:
    - get: gpupgrade_src
      trigger: true
    - get: bats
  - task: noinstall-tests
    file: gpupgrade_src/ci/tasks/noinstall-tests.yml
  on_failure:
    <<: *slack_alert

{{range .CheckJobs}}
- name: {{.Name}}
  plan:
  - in_parallel:
    - get: gpupgrade_src
      trigger: true
    - get: gpdb_src_source
      resource: gpdb{{.Source}}_src
    - get: bats
    - get: rpm_gpdb_source
      resource: rpm_gpdb{{.Source}}_centos7
      trigger: true
    - get: rpm_gpdb_target
      resource: rpm_gpdb{{.Target}}_centos7
      trigger: true
  - task: install-tests
    file: gpupgrade_src/ci/tasks/install-tests.yml
    params:
      SOURCE_PACKAGE: greenplum-db-{{.Source}}
      TARGET_PACKAGE: greenplum-db-{{.Target}}
  on_failure:
    <<: *slack_alert
{{end -}}

{{range .UpgradeJobs}}
- name: {{ .Name }}
  serial_groups: [{{ .BaseName }}]
  # Specifying serial groups so that only one platform runs at a time. For
  # example, 5-to-6-centos7 will only run after 5-to-6-centos6 completes. This
  # will prevent concourse from becoming overloaded.
  plan:
    - in_parallel:
        - get: bin_gpupgrade
          trigger: true
          passed: [ build ]
        - get: gpupgrade_src
          passed: [ build ]
        - get: rpm_gpdb_source
          resource: rpm_gpdb{{.Source}}_centos{{.CentosVersion}}
          trigger: true
        {{- if ne .Source .Target }}
        - get: rpm_gpdb_target
          resource: rpm_gpdb{{.Target}}_centos{{.CentosVersion}}
          trigger: true
        {{- end }}
        - get: ccp_src
        {{- if .RetailDemo }}
        - get: retail_demo_src
        {{- else }}
        # FIXME: this is not guaranteed to be the same dump generated by the
        # above binary...
        - get: sqldump
          {{- if eq (majorVersion .Source) "5" }}
          resource: gpdb5_icw_planner_centos6_dump
          {{- else }}
          resource: dump_gpdb6_icw_gporca_centos6
          {{- end }}
        {{- end }}
    - put: terraform
      params:
        <<: *ccp_default_params
        vars:
          {{- if .PrimariesOnly}}
          mirrors: false
          {{- else if not .NoStandby}}
          standby_master: true
          {{- end}}
          instance_type: n1-standard-2
          number_of_nodes: 4
          PLATFORM: centos{{.CentosVersion}}
          # Decrease the reap time from the default of 8 hours now that there are
          # both centos6 and centos7 jobs in order to not overload concourse.
          ccp_reap_minutes: 180
    - task: gen_source_cluster
      file: ccp_src/ci/tasks/gen_cluster.yml
      params:
        <<: *ccp_gen_cluster_default_params
        PLATFORM: centos{{.CentosVersion}}
        GPDB_RPM: true
      input_mapping:
        gpdb_rpm: rpm_gpdb_source
    - task: gpinitsystem_source_cluster
      file: ccp_src/ci/tasks/gpinitsystem.yml
    - task: prepare_source_and_target_installations
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: alpine
            tag: latest
        inputs:
          - name: gpupgrade_src
          - name: cluster_env_files
          {{- if ne .Source .Target }}
          - name: rpm_gpdb_target
          {{- end }}
        run:
          path: gpupgrade_src/ci/scripts/prepare-source-and-target-installations.sh
          args:
            - greenplum-db-{{majorVersion .Source}}
            - greenplum-db-{{majorVersion .Target}}
    {{- if .RetailDemo }}
    - task: load_retail_data
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: pivotaldata/gpdb6-centos7-test
            tag: latest
        inputs:
          - name: gpupgrade_src
          - name: retail_demo_src
          - name: ccp_src
          - name: cluster_env_files
        run:
          path: gpupgrade_src/ci/scripts/load-retail-data.bash
    {{- else }}
    - task: load_dump
      file: gpupgrade_src/ci/tasks/load-dump.yml
    {{- end }}
    - task: upgrade_cluster
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: pivotaldata/gpdb6-centos7-test-golang
            tag: "latest"
        inputs:
        - name: terraform
        - name: ccp_src
        - name: cluster_env_files
        - name: gpupgrade_src
        - name: bin_gpupgrade
        run:
          path: gpupgrade_src/ci/scripts/upgrade-cluster.bash
      params:
        {{- if ne .Source .Target }}
        FILTER_DIFF: 1
        {{- end }}
        {{- if .UseLinkMode}}
        USE_LINK_MODE: 1
        {{- end}}
        {{- if .RetailDemo}}
        DIFF_FILE: retail_demo.diff
        {{- end }}
    {{- if not .NoStandby -}}
    {{- if not .PrimariesOnly }}
    - task: validate_mirrors_and_standby
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: pivotaldata/gpdb6-centos7-test-golang
            tag: "latest"
        inputs:
          - name: gpupgrade_src
          - name: cluster_env_files
        run:
          path: gpupgrade_src/ci/scripts/validate-mirrors-and-standby.bash
    {{- end -}}
    {{- end }}
  ensure:
    <<: *set_failed
  on_success:
    <<: *ccp_destroy
  on_failure:
    <<: *slack_alert
{{end -}}

{{range .MultihostBatsJobs}}
- name: {{ .Name }}
  serial_groups: [{{ .BaseName }}]
  # Specifying serial groups so that only one platform runs at a time. For
  # example, 5-to-6-centos7 will only run after 5-to-6-centos6 completes. This
  # will prevent concourse from becoming overloaded.
  plan:
    - in_parallel:
        - get: bin_gpupgrade
          trigger: true
          passed: [ build ]
        - get: gpupgrade_src
          passed: [ build ]
        - get: rpm_gpdb_source
          resource: rpm_gpdb{{.Source}}_centos{{.CentosVersion}}
          trigger: true
        {{- if ne .Source .Target }}
        - get: rpm_gpdb_target
          resource: rpm_gpdb{{.Target}}_centos{{.CentosVersion}}
          trigger: true
        {{- end }}
        - get: ccp_src
        - get: bats
    - put: terraform
      params:
        <<: *ccp_default_params
        vars:
          standby_master: true
          instance_type: n1-standard-2
          number_of_nodes: 4
          PLATFORM: centos{{.CentosVersion}}
          # Decrease the reap time from the default of 8 hours now that there are
          # both centos6 and centos7 jobs in order to not overload concourse.
          ccp_reap_minutes: 180
    - task: gen_source_cluster
      file: ccp_src/ci/tasks/gen_cluster.yml
      params:
        <<: *ccp_gen_cluster_default_params
        PLATFORM: centos{{.CentosVersion}}
        GPDB_RPM: true
      input_mapping:
        gpdb_rpm: rpm_gpdb_source
    - task: gpinitsystem_source_cluster
      file: ccp_src/ci/tasks/gpinitsystem.yml
    - task: prepare_source_and_target_installations
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: alpine
            tag: latest
        inputs:
          - name: gpupgrade_src
          - name: cluster_env_files
          {{- if ne .Source .Target }}
          - name: rpm_gpdb_target
          {{- end }}
        run:
          path: gpupgrade_src/ci/scripts/prepare-source-and-target-installations.sh
          args:
            - greenplum-db-{{majorVersion .Source}}
            - greenplum-db-{{majorVersion .Target}}
    - task: run_bats
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: pivotaldata/gpdb6-centos7-test-golang
            tag: "latest"
        inputs:
          - name: terraform
          - name: ccp_src
          - name: cluster_env_files
          - name: gpupgrade_src
          - name: bin_gpupgrade
          - name: bats
        run:
          path: gpupgrade_src/ci/scripts/bats-on-cluster.bash
      params:
  ensure:
    <<: *set_failed
  on_success:
    <<: *ccp_destroy
  on_failure:
    <<: *slack_alert
{{end -}}

- name: publish-release-candidate
  plan:
    - in_parallel:
      - get: gpupgrade_src
        trigger: true
        passed:
          - build
          - noinstall-tests
          {{- range .CheckJobs}}
          - {{ .Name }}
          {{- end}}
          {{- range .UpgradeJobs}}
          - {{ .Name }}
          {{- end}}
          {{- range .MultihostBatsJobs}}
          - {{ .Name }}
          {{- end}}
      - get: bin_gpupgrade
        passed:
          - build
          {{- range .UpgradeJobs}}
          - {{ .Name }}
          {{- end}}
          {{- range .MultihostBatsJobs}}
          - {{ .Name }}
          {{- end}}
    - task: version-rc
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: golang
            tag: '1.15'
        inputs:
          - name: gpupgrade_src
          - name: bin_gpupgrade
        outputs:
          - name: gpupgrade_bin_path
        run:
          path: gpupgrade_src/ci/scripts/version-rc.sh
    - put: bin_gpupgrade_rc
      params:
        file: gpupgrade_bin_path/gpupgrade-rc-*-linux_x86_64
  on_failure:
    <<: *slack_alert
